### ISSUE TITLE
Smart vs Straight Quotes

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki-manual#382]
The style guide recommends: 

> Use double quotes, `"`, instead of single quotes, `'`.

I think aesthetically, curly quotes look fabulous (with right fonts) but the straights do not. Opinions welcome.

**Comment by adeluccar** [comment]
You’re right. Installed mdbook to check. Build works. Adding that one-liner in the toml in the output section does the trick. And it does look better.

```toml
[output.html]
git-repository-url = "https://github.com/ankitects/anki-manual/"
cname = "docs.ankiweb.net"
additional-css = ["css/misc.css", "css/kbd.css"]
curly-quotes = true
mathjax-support = true
```

![Image](https://github.com/user-attachments/assets/6216ac52-3b93-4599-986c-8300bd515354)
